# for AWS code build
version: 0.2

env:
  param_store:
    AWS_ACCESS_KEY_ID: "code-build-access-key"
    AWS_SECRET_ACCESS_KEY: "code-build-secret-key"

phases:
  install:
    commands:
      - echo Install started on `date`
      - curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install yarn python-pip nodejs zip --yes
      - apt-get install python-pip
      - pip install awscli --upgrade --user
      - ln -s /usr/bin/nodejs /usr/bin/node
      - echo Install completed on `date` 
  build:
    commands:
      - echo Build started on `date`
      - make ENVIRONMENT_FILE=$EnvFileLocation
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Cleanup started on `date`
      - ~/.local/bin/aws s3 cp $EnvFolder prodenv/ --recursive
      - ~/.local/bin/aws s3 cp $AppSpecFile appspec.yml
      - ~/.local/bin/aws s3 cp $ProdScripts prodscripts/ --recursive
      - echo Cleanup finished on `date`
artifacts:
  files:
    - webdist/*
    - webdist/**/*
    - Hacksite
    - prodenv/*
    - prodscripts/*
    - appspec.yml 
